/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizgame;

import java.sql.ResultSet;
import javax.swing.*;
import java.util.Enumeration;
/**
 *
 * @author jagen
 */

public class quest extends javax.swing.JFrame {

    /**
     * Creates new form quest
     */
    public  ResultSet rs;
    int qno = 1;
    public static String userName ;
    static String mode;
    public int score = 0;
      
    public quest(){
        
      initComponents();
      
       }
    
    
    public quest(ResultSet rs,String userName,String mode) {
        
        initComponents();
           this.rs = rs;
         
           this.userName = userName;
          this.mode = mode;
           this.display();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.ButtonGroup();
        question = new javax.swing.JLabel();
        opt2 = new javax.swing.JRadioButton();
        opt1 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        nxtbtn = new javax.swing.JButton();
        srno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));

        question.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        question.setText("jLabel1");
        question.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        options.add(opt2);
        opt2.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        opt2.setText("jRadioButton1");
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });

        options.add(opt1);
        opt1.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        opt1.setText("jRadioButton1");
        opt1.setBorder(null);

        options.add(opt3);
        opt3.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        opt3.setText("jRadioButton1");

        options.add(opt4);
        opt4.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        opt4.setText("jRadioButton1");
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });

        nxtbtn.setText("Next");
        nxtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtbtnActionPerformed(evt);
            }
        });

        srno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        srno.setText("jLabel1");
        srno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nxtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(srno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 327, Short.MAX_VALUE)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(opt1)
                .addGap(12, 12, 12)
                .addComponent(opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt3)
                .addGap(18, 18, 18)
                .addComponent(opt4)
                .addGap(33, 33, 33)
                .addComponent(nxtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nxtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtbtnActionPerformed
               boolean selected = false;
        for (Enumeration<AbstractButton> buttons = options.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
try{    
    
            if (button.isSelected()) {
                if(button.getText().equals(rs.getString(8))) {
                this.score++;
           
                }
              
                        this.display(); 
            }
           
            }catch(Exception e)
  {
             JOptionPane.showMessageDialog(this, e);
  } }
//      if(selected == false){
//            
//                JOptionPane.showMessageDialog(this,"Please select any one option");
//            
//              }
          // TODO add your handling code here:
                        
    }//GEN-LAST:event_nxtbtnActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quest().setVisible(true);
            }
        });
    }
    
    public  void  display(){
        
     try{
         
     if( this.rs.next()){
         options.clearSelection();
      srno.setText(Integer.toString(qno));
      qno++;
      String q = "<HTML>  " + rs.getString(2) + "</HTML>";
        question.setText(q);
        opt1.setText(rs.getString(4));
        opt2.setText(rs.getString(5));
        opt3.setText(rs.getString(6));
        opt4.setText(rs.getString(7));
       
     }
     else{
     score sc = new score(userName,this.mode,this.score);
     
       System.out.print(userName);
    sc.setVisible(true);
     this.dispose();
//         nxtbtn.setText(userName);
     }
       }catch(Exception e)
  {
             JOptionPane.showMessageDialog(this, e);
  }
    }  
    
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nxtbtn;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.ButtonGroup options;
    private javax.swing.JLabel question;
    private javax.swing.JLabel srno;
    // End of variables declaration//GEN-END:variables
}
